/*
 * Robot Rally Game logic engine
 *
 * This api controlls the flow of a game and provides it's data. It is desiged to be RESTfull so the structure works simmilar as file system. The service will run and only work in a local network, `game.host` is the IP of the Computer hosting the game and will be found via a IP scan
 *
 * The version of the OpenAPI document: v0.4.1b0
 * Contact: nbrugger@student.tgm.ac.at
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Tgm.Roborally.Server.Converters;
using Tgm.Roborally.Server.Engine;

namespace Tgm.Roborally.Server.Models {
	/// <summary>
	/// Happens when a entity takes damage
	/// </summary>
	[DataContract]
	public partial class DamageEvent : IEquatable<DamageEvent>, Event {
		/// <summary>
		/// The unique identification of this entity. &lt;br&gt; *!!!* This is not the id of the player&lt;br&gt; This value will be autogenerated by the api and is read only
		/// </summary>
		/// <value>The unique identification of this entity. &lt;br&gt; *!!!* This is not the id of the player&lt;br&gt; This value will be autogenerated by the api and is read only</value>
		[DataMember(Name = "entity", EmitDefaultValue = false)]
		public int Entity { get; set; }

		/// <summary>
		/// The number of damage points
		/// </summary>
		/// <value>The number of damage points</value>
		[Range(0, 5)]
		[DataMember(Name = "ammount", EmitDefaultValue = false)]
		public int Ammount { get; set; }

		/// <summary>
		/// Returns the string presentation of the object
		/// </summary>
		/// <returns>String presentation of the object</returns>
		public override string ToString() {
			var sb = new StringBuilder();
			sb.Append("class DamageEvent {\n");
			sb.Append("  Entity: ").Append(Entity).Append("\n");
			sb.Append("  Ammount: ").Append(Ammount).Append("\n");
			sb.Append("}\n");
			return sb.ToString();
		}

		public EventType GetEventType() => EventType.Damage;

		/// <summary>
		/// Returns the JSON string presentation of the object
		/// </summary>
		/// <returns>JSON string presentation of the object</returns>
		public string ToJson() {
			return JsonConvert.SerializeObject(this, Formatting.Indented);
		}

		/// <summary>
		/// Returns true if objects are equal
		/// </summary>
		/// <param name="obj">Object to be compared</param>
		/// <returns>Boolean</returns>
		public override bool Equals(object obj) {
			if (obj is null) return false;
			if (ReferenceEquals(this, obj)) return true;
			return obj.GetType() == GetType() && Equals((DamageEvent) obj);
		}

		/// <summary>
		/// Returns true if DamageEvent instances are equal
		/// </summary>
		/// <param name="other">Instance of DamageEvent to be compared</param>
		/// <returns>Boolean</returns>
		public bool Equals(DamageEvent other) {
			if (other is null) return false;
			if (ReferenceEquals(this, other)) return true;

			return
				(
					Entity == other.Entity ||
					Entity.Equals(other.Entity)
				) &&
				(
					Ammount == other.Ammount ||
					Ammount.Equals(other.Ammount)
				);
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode() {
			unchecked // Overflow is fine, just wrap
			{
				var hashCode = 41;
				// Suitable nullity checks etc, of course :)

				hashCode = hashCode * 59 + Entity.GetHashCode();

				hashCode = hashCode * 59 + Ammount.GetHashCode();
				return hashCode;
			}
		}

		#region Operators

		#pragma warning disable 1591

		public static bool operator ==(DamageEvent left, DamageEvent right) {
			return Equals(left, right);
		}

		public static bool operator !=(DamageEvent left, DamageEvent right) {
			return !Equals(left, right);
		}

		#pragma warning restore 1591

		#endregion Operators
	}
}