/*
 * Robot Rally Game logic engine
 *
 * This api controlls the flow of a game and provides it's data. It is desiged to be RESTfull so the structure works simmilar as file system. The service will run and only work in a local network, `game.host` is the IP of the Computer hosting the game and will be found via a IP scan
 *
 * The version of the OpenAPI document: v0.8.2
 * Contact: nbrugger@student.tgm.ac.at
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Tgm.Roborally.Server.Converters;

namespace Tgm.Roborally.Server.Models {
	/// <summary>
	/// Occurs when the next phase of the round starts
	/// </summary>
	[DataContract]
	public partial class RoundPhaseChangedEvent : IEquatable<RoundPhaseChangedEvent> {
		/// <summary>
		/// Gets or Sets Phase
		/// </summary>
		[DataMember(Name = "phase", EmitDefaultValue = false)]
		public RoundPhase Phase { get; set; }

		/// <summary>
		/// Returns the string presentation of the object
		/// </summary>
		/// <returns>String presentation of the object</returns>
		public override string ToString() {
			var sb = new StringBuilder();
			sb.Append("class RoundPhaseChangedEvent {\n");
			sb.Append("  Phase: ").Append(Phase).Append("\n");
			sb.Append("}\n");
			return sb.ToString();
		}

		/// <summary>
		/// Returns the JSON string presentation of the object
		/// </summary>
		/// <returns>JSON string presentation of the object</returns>
		public string ToJson() {
			return JsonConvert.SerializeObject(this, Formatting.Indented);
		}

		/// <summary>
		/// Returns true if objects are equal
		/// </summary>
		/// <param name="obj">Object to be compared</param>
		/// <returns>Boolean</returns>
		public override bool Equals(object obj) {
			if (obj is null) return false;
			if (ReferenceEquals(this, obj)) return true;
			return obj.GetType() == GetType() && Equals((RoundPhaseChangedEvent) obj);
		}

		/// <summary>
		/// Returns true if RoundPhaseChangedEvent instances are equal
		/// </summary>
		/// <param name="other">Instance of RoundPhaseChangedEvent to be compared</param>
		/// <returns>Boolean</returns>
		public bool Equals(RoundPhaseChangedEvent other) {
			if (other is null) return false;
			if (ReferenceEquals(this, other)) return true;

			return
				(
					Phase == other.Phase ||
					Phase.Equals(other.Phase)
				);
		}

		/// <summary>
		/// Gets the hash code
		/// </summary>
		/// <returns>Hash code</returns>
		public override int GetHashCode() {
			unchecked // Overflow is fine, just wrap
			{
				var hashCode = 41;
				// Suitable nullity checks etc, of course :)

				hashCode = hashCode * 59 + Phase.GetHashCode();
				return hashCode;
			}
		}

		#region Operators

		#pragma warning disable 1591

		public static bool operator ==(RoundPhaseChangedEvent left, RoundPhaseChangedEvent right) {
			return Equals(left, right);
		}

		public static bool operator !=(RoundPhaseChangedEvent left, RoundPhaseChangedEvent right) {
			return !Equals(left, right);
		}

		#pragma warning restore 1591

		#endregion Operators
	}
}