/* 
 * Robot Rally Game logic engine
 *
 * This api controlls the flow of a game and provides it's data. It is desiged to be RESTfull so the structure works simmilar as file system. The service will run and only work in a local network, `game.host` is the IP of the Computer hosting the game and will be found via a IP scan
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nbrugger@student.tgm.ac.at
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tgm.Roborally.Api.Api;
using Tgm.Roborally.Api.Model;
using Tgm.Roborally.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tgm.Roborally.Api.Test
{
    /// <summary>
    ///  Class for testing RobotInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobotInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobotInfo
        //private RobotInfo instance;

        public RobotInfoTests()
        {
            // TODO uncomment below to create an instance of RobotInfo
            //instance = new RobotInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobotInfo
        /// </summary>
        [Fact]
        public void RobotInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RobotInfo
            //Assert.IsInstanceOfType<RobotInfo> (instance, "variable 'instance' is a RobotInfo");
        }


        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Fact]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'EnergyCubes'
        /// </summary>
        [Fact]
        public void EnergyCubesTest()
        {
            // TODO unit test for the property 'EnergyCubes'
        }
        /// <summary>
        /// Test the property 'Health'
        /// </summary>
        [Fact]
        public void HealthTest()
        {
            // TODO unit test for the property 'Health'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Virtual'
        /// </summary>
        [Fact]
        public void VirtualTest()
        {
            // TODO unit test for the property 'Virtual'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'OnTurn'
        /// </summary>
        [Fact]
        public void OnTurnTest()
        {
            // TODO unit test for the property 'OnTurn'
        }
        /// <summary>
        /// Test the property 'IsMine'
        /// </summary>
        [Fact]
        public void IsMineTest()
        {
            // TODO unit test for the property 'IsMine'
        }
        /// <summary>
        /// Test the property 'HandCards'
        /// </summary>
        [Fact]
        public void HandCardsTest()
        {
            // TODO unit test for the property 'HandCards'
        }
        /// <summary>
        /// Test the property 'Attitude'
        /// </summary>
        [Fact]
        public void AttitudeTest()
        {
            // TODO unit test for the property 'Attitude'
        }

    }

}
