:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\Tgm.Roborally.Server
dotnet build src\Tgm.Roborally.Server
echo Now, run the following to start the project: dotnet run -p src\Tgm.Roborally.Server\Tgm.Roborally.Server.csproj --launch-profile web. OR use the generated executeable src\Tgm.Roborally.Server\bin\Release\netcore3.1\release
echo.
