/* 
 * Robot Rally Game logic engine
 *
 * This api controlls the flow of a game and provides it's data. It is desiged to be RESTfull so the structure works simmilar as file system. The service will run and only work in a local network, `game.host` is the IP of the Computer hosting the game and will be found via a IP scan
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nbrugger@student.tgm.ac.at
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tgm.Roborally.Api.Client.OpenAPIDateConverter;

namespace Tgm.Roborally.Api.Model
{
    /// <summary>
    /// The type defines the function of a tile and how it is displayed. The behaviour is unknown to the client
    /// </summary>
    /// <value>The type defines the function of a tile and how it is displayed. The behaviour is unknown to the client</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TileType
    {
        /// <summary>
        /// Enum Normal for value: normal
        /// </summary>
        [EnumMember(Value = "normal")]
        Normal = 1,

        /// <summary>
        /// Enum Rotator for value: rotator
        /// </summary>
        [EnumMember(Value = "rotator")]
        Rotator = 2,

        /// <summary>
        /// Enum Band for value: band
        /// </summary>
        [EnumMember(Value = "band")]
        Band = 3,

        /// <summary>
        /// Enum Hole for value: hole
        /// </summary>
        [EnumMember(Value = "hole")]
        Hole = 4,

        /// <summary>
        /// Enum Wall for value: wall
        /// </summary>
        [EnumMember(Value = "wall")]
        Wall = 5,

        /// <summary>
        /// Enum Priocore for value: prio_core
        /// </summary>
        [EnumMember(Value = "prio_core")]
        Priocore = 6

    }

}
